version: '3.9'
services:
  backend:
    image: "wasduio/diet:v1.2"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      spring.datasource.password: ${RDS_PASSWORD}
      spring.datasource.username: ${RDS_USERNAME}