version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set execute permissions for mvnw
          command: chmod +x mvnw
      - run:
          name: Build the Java project
          command: ./mvnw clean install
