version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set execute permissions for mvnw
          command: chmod +x mvnw
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build the Java project without tests using a specific profile
          command: ./mvnw clean install -DskipTests=true -P native
      - run:
          name: Build docker image
          command: docker build -t diet .
      - run:
          name: Build the Java project using a specific profile
          command: ./mvnw clean install -P native